import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-blue": "#0076CE",
        "brand-pink": "#E91E63",
        "logo-pink": "#E91E63",
        "logo-blue": "#2196F3",
        "tertiary-fixed-dim": "#cbe6d4",
        "error-container": "#fe8983",
        "on-surface-variant": "#586064",
        "secondary-fixed-dim": "#c5d6e9",
        "on-surface": "#2b3437",
        "on-tertiary-fixed-variant": "#506859",
        "primary": "#1B263B",
        "inverse-on-surface": "#9b9d9e",
        "on-secondary-container": "#435363",
        "surface-container": "#eaeff1",
        "on-error": "#fff7f6",
        "outline-variant": "#abb3b7",
        "on-error-container": "#752121",
        "on-secondary-fixed": "#314150",
        "on-primary-fixed": "#353f56",
        "error-dim": "#4e0309",
        "surface-variant": "#dbe4e7",
        "secondary-fixed": "#d3e4f7",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#f7f7ff",
        "tertiary-container": "#FCE4EC",
        "on-secondary": "#f6f9ff",
        "on-tertiary": "#e6ffed",
        "on-background": "#2b3437",
        "tertiary-dim": "#40584a",
        "surface-dim": "#d1dce0",
        "secondary-container": "#d3e4f7",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed-variant": "#4d5d6d",
        "surface-container-low": "#f1f4f6",
        "on-primary-container": "#475269",
        "surface-container-highest": "#dbe4e7",
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-tint": "#1B263B",
        "on-primary-fixed-variant": "#515c73",
        "inverse-primary": "#d7e2ff",
        "error": "#9f403d",
        "primary-container": "#d7e2ff",
        "primary-dim": "#48526a",
        "outline": "#737c7f",
        "inverse-surface": "#0c0f10",
        "secondary-dim": "#445564",
        "tertiary-fixed": "#d9f5e2",
        "on-tertiary-fixed": "#344b3e",
        "background": "#f8f9fa",
        "tertiary": "#4c6456",
        "on-tertiary-container": "#880E4F",
        "secondary": "#506171",
        "primary-fixed-dim": "#c9d4f0",
        "surface-container-high": "#e3e9ec",
        "background-light": "#f6f7f7",
        "background-dark": "#15181d",
      },
      fontFamily: {
        headline: ["ui-serif", "Georgia", "Cambria", "\"Times New Roman\"", "serif"],
        display: ["ui-serif", "Georgia", "Cambria", "\"Times New Roman\"", "serif"],
        body: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "\"Segoe UI\"",
          "Roboto",
          "\"Helvetica Neue\"",
          "Arial",
          "sans-serif",
        ],
        label: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          "\"Segoe UI\"",
          "Roboto",
          "\"Helvetica Neue\"",
          "Arial",
          "sans-serif",
        ],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    containerQueries,
    forms,
  ],
};
export default config;
