import { Buffer } from "node:buffer";
import { NextResponse } from "next/server";

import { getAdminContext } from "@/lib/auth/current-user";
import { getStorage } from "@/lib/storage";

const MAX_BYTES = 12 * 1024 * 1024;

// Storage keys generated by generateMediaKey() are <scope>/YYYY/MM/<uuid>.<ext>.
const KEY_PATTERN = /^[a-z0-9-]+\/\d{4}\/\d{2}\/[a-f0-9-]{8,}\.[a-z0-9]+$/i;

export const dynamic = "force-dynamic";

/**
 * Local-driver upload endpoint. In dev, the browser PUTs the file body here
 * after `requestUploadAction` returns a synthetic upload URL pointing at this
 * route. In production with R2, the browser uploads directly to R2 and this
 * route is never used.
 */
export async function PUT(request: Request) {
  const ctx = await getAdminContext();
  if (!ctx.authenticated) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  const storage = getStorage();
  if (storage.driver !== "local") {
    return NextResponse.json(
      { error: "Upload route is only used by the local driver." },
      { status: 400 },
    );
  }

  const url = new URL(request.url);
  const key = url.searchParams.get("key");
  if (!key || !KEY_PATTERN.test(key)) {
    return NextResponse.json({ error: "Invalid key." }, { status: 400 });
  }

  const contentType = request.headers.get("content-type") ?? "application/octet-stream";

  const arrayBuffer = await request.arrayBuffer();
  if (arrayBuffer.byteLength === 0) {
    return NextResponse.json({ error: "Empty body." }, { status: 400 });
  }
  if (arrayBuffer.byteLength > MAX_BYTES) {
    return NextResponse.json({ error: "File too large." }, { status: 413 });
  }

  try {
    const result = await storage.put({
      key,
      contentType,
      body: Buffer.from(arrayBuffer),
    });
    return NextResponse.json({ ok: true, publicUrl: result.publicUrl });
  } catch (error) {
    console.error("[api] /admin/media/upload failed", error);
    return NextResponse.json({ error: "Upload failed." }, { status: 500 });
  }
}
